function [h,ax,choices] = showequalmoves(h1,h,ax)
    global students;
    choices = [];
    hold on;
    y=get(h1,'YData');
    y2=get(h,'YData');
    x=get(ax,'XTickLabel');
    xdata=get(h,'XData');
    move=1;
    for i=1:numel(students)
        if students(i).strengtharea1 == students(i).strengtharea2
            %% draw line from top of area1 to area2
            [xaf,yaf]=ds2nfu([xdata(strcmp(students(i).area1,x)) ...
                xdata(strcmp(students(i).area2,x))], ...
                [y(strcmp(students(i).area1,x)) ...
                y2(strcmp(students(i).area2,x))]);
            [centerx,centery]=ds2nfu((xdata(strcmp(students(i).area1,x)) ...
                +xdata(strcmp(students(i).area2,x)))/2, ...
                (y(strcmp(students(i).area1,x)) ...
                +y2(strcmp(students(i).area2,x)))/2);
            a=annotation('arrow',xaf,yaf);
            ui=uicontrol('Style','pushbutton');
            set(ui,'String',num2str(move),...
                'Units','normalized','Position',[centerx centery 0.02 0.05],...
                'UserData',struct('studentno',i,...
                'startpos',find(strcmp(students(i).area1,x)),...
                'stoppos',find(strcmp(students(i).area2,x)),...
                'h',h,'h1',h1,'a',a,'ui',ui),...
                'Callback',@pushbutton_Callback);
            move=move+1;
        end
    end
    ui=uicontrol('Style','pushbutton','String','Done','Position',[0 0 50 20],...
        'Callback',@done_moving_students);
end